### ISSUE TITLE
Binary fastq files created

### ISSUE THREAD

**Issue by michoug** [softwarecomputationalbiologyufpa/gcsplit#1]
Hi,
The temporary fastq files in the gcsplit folder were binary files.
I think it's due to the fact that I gave gz compress files intially
Best
Greg

**Comment by mirand863** [comment]
Hello @michoug,

Sorry for the late reply.

Unfortunately GCSplit does not work with compressed files yet, so you would need to extract the files with gunzip before running it. However, I will see if I can add this feature to the program.

Thank you for the feedback,
Fábio

**Comment by michoug** [comment]
Thanks!
